### ISSUE TITLE
filter are not updated with the ajax call

### ISSUE THREAD

**Issue by Tahuna1** [Web200/magento2-elasticsuite-ajax#1]
i have this issue on mulitselect filter:
when i check an filter the results are updated, but not the filter (show filter options and counts behind the options)
when i go into the address bar in the browser and make page reload with current filter url the filters are updated as normal.

Example: 'DC input voltage' shows no changes after the ajax call (see filter-after-ajax-call.png), but changes are shown after an hard page reload with the current filter url (filter-after-page-load.png
![filter-after-ajax-call](https://user-images.githubusercontent.com/16258046/106118279-35a3b380-6154-11eb-84fb-879eab5e1cd0.png)
![filter-after-page-load](https://user-images.githubusercontent.com/16258046/106118285-363c4a00-6154-11eb-89a6-9225301a2dfc.png)

)

**Comment by kpitn** [comment]
Hi @Tahuna1,

I just push a fix for this issues on master.

**Comment by Tahuna1** [comment]
looks good now thx
