### ISSUE TITLE
Changing the sort order or direction resets the filter options

### ISSUE THREAD

**Issue by mfickers** [Web200/magento2-elasticsuite-ajax#11]
When interacting with the sorting options, all already applied filters will be reset.

For us, this was fixed by applying the changes from #8.

# Steps to reproduce
1. Open category page
2. Select some filter options
3. Change the "Sort by" to another value

# Expected result
Product grid updated with the chosen filter options and sorting

# Actual result
Sorting is applied, but filter options are lost

**Comment by kpitn** [comment]
This issues is fix in last version 1.0.0
