### ISSUE TITLE
AJAX caching not working correctly with default Magento Varnish configuration

### ISSUE THREAD

**Issue by mfickers** [Web200/magento2-elasticsuite-ajax#15]
v1.0.0 has added caching for AJAX requests. Since upgrading, sometimes when loading product listing pages, instead of the regular page, there will just be a huge JSON returned.

The AJAX caching is done by adding a flag to the Magento full page cache identifier, if the HTTP_X_REQUESTED_WITH header is set to "XMLHttpRequest". The Magento full page cache will then differentiate between regular requests and AJAX requests.

When using Magento with Varnish, this identifier will not be used to resolve the cache objects. Instead, the default Magento varnish configuration file uses the Varnish default hashing strategy (URL and either Host header, or server IP), plus the X-Magento-Vary header. There is no distinction between regular and AJAX requests with the default configuration.

This results in mixups between AJAX and regular requests.

## Steps to reproduce
1. Set up Varnish with Magento default configuration
1. Go to a category page
1. Use the pagination to go to page 2
1. Product grid will be loaded via AJAX
1. Reload the page

## Expected result
* Page loads normally

## Actual result
* Instead of the category page, the JSON of the AJAX call will be rendered

**Comment by mfickers** [comment]
To fix this issue, the vcl_hash subroutine of the Varnish configuration needs to be extended with an additional hash_data for the X-Requested-With header:

```vcl
sub vcl_hash {
    ...

    # Sort AJAX requests distinct from regular requests
    if (req.http.X-Requested-With == "XMLHttpRequest"){
        hash_data(req.http.X-Requested-With);
    }

    ...
}
```

**Comment by kpitn** [comment]
I add your code in the readme. Thanks

**Comment by norgeindian** [comment]
@mfickers , this way, the caching is disabled for all AJAX requests on the whole page, correct?
Isn't there any other way to handle that? Maybe with a URL parameter like `ìs_ajax=1`? That would also make Varnish realize, that this is different as far as I know.

**Comment by mfickers** [comment]
@norgeindian, caching for AJAX requests should not be disabled. Rather, Varnish will treat requests differently based on the X-Requested-With header. So the same URL will be cached twice, once for AJAX and once for regular requests.
