### ISSUE TITLE
Problems with the return url 

### ISSUE THREAD

**Issue by Tahuna1** [Web200/magento2-elasticsuite-ajax#3]
when i used the filter and then add an product on the comparison list, i will be redirected back to the json service url instead of the category page:

![Screenshot 2021-03-22 at 09 33 39](https://user-images.githubusercontent.com/16258046/111977243-cd919e00-8b02-11eb-848e-53040f37f774.png)

<a href="#" class="action tocompare" data-post="{&quot;action&quot;:&quot;https:\/\/products.pulspower.com\/en\/catalog\/product_compare\/add\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;72&quot;,&quot;uenc&quot;:&quot;aHR0cHM6Ly9wcm9kdWN0cy5wdWxzcG93ZXIuY29tL2VuL3BhcmFtZXRlci1zZWFyY2guaHRtbD9fPTE2MTY0MDkxNjQ0MDQmY2F0ZWdvcnlfbmFtZXMlNUIwJTVEPTMtcGhhc2UlMjBwb3dlciUyMHN1cHBsaWVz&quot;}}" title="Add to Compare"></a>

**Comment by kpitn** [comment]
Hi @Tahuna1 ,

Thanx for reporting.
Can you test the last release ?
It was ajax cache mix with non ajax cache.

**Comment by Tahuna1** [comment]
thanks for the fast fix, it looks good.

**Comment by Tahuna1** [comment]
we test it again and its strange because sometimes its working and some times not, can you take a look at this again, pls
thx

**Comment by kpitn** [comment]
It was a cache problem, i can't reproduce it since the last fix : https://github.com/Web200/magento2-elasticsuite-ajax/commit/067b8c94db533b6ce37a50734223bfd75a611de6

Can you make a small video to show me the problem ?

**Comment by Tahuna1** [comment]
https://mediawavegmbh-my.sharepoint.com/:v:/g/personal/jvheynitz_mediawave_de/EVvBc4FcKH5GoZm3YwpwL_wBOuJ15jNfpl6iT8AFDNVO8w?e=Bcrudj

**Comment by kpitn** [comment]
Are you sure, you have update the module and have this code line :

`
 $this->context->setValue('ajax', true, false);
`

And empty cache, I can't reproduce with the last version.

**Comment by Tahuna1** [comment]
yes, i have updated the module:
name     : web200/magento-elasticsuite-ajax
descrip. : Magento 2 Module to add ajax navigation to elasticsuite module
keywords : 
versions : * v0.7.6

i am sure that i have the code line (i flushed the magento cache and my browser cache), it dosn´t happen very time (like before the fix) ... i would say 1 out of 5 times

**Comment by Janvh** [comment]
Hi kpitn,

I'm a colleague of Tahuna1. Thanks for your effort!

The testcase is as follows:

1. Open incognito window
2. Go to https://products.pulspower.com/en/parameter-search.html
2. Select filter 5A for filter _DC Output current_
3. Add product to comparison list

In this case I always get the error

**Comment by kpitn** [comment]
I can't find a solution for you, without debugging your magento.

What is see in your website :

* Go to : https://products.pulspower.com/en/parameter-search.html
* Select a filter : XHR => https://products.pulspower.com/en/parameter-search.html?output_current_parameter_searc%5B0%5D=0.63A&_=1617308070147
* You click on compare and you are redirect to the same url than the XHR request : https://products.pulspower.com/en/parameter-search.html?output_current_parameter_searc%5B0%5D=0.63A&_=1617308070147

In your magento the XHR request is in cache (it's ok), and if you just go to : https://products.pulspower.com/en/parameter-search.html?output_current_parameter_searc%5B0%5D=0.63A&_=1617308070147
You have the xhr content display even without XHR (the cached non xhr page is not working)


I have a magento 2.4 with sample data and  all cache enable

* Go to a category
* Select a filter : the ajax request is call
* Add to compare: the redirect page is call

Even if the url are the same (Ajax and non Ajax request) the response is display in json when XHR and in html without.
See video : https://youtu.be/sxE3zwC5moM
