### ISSUE TITLE
Filter count not updated since v0.7

### ISSUE THREAD

**Issue by Tahuna1** [Web200/magento2-elasticsuite-ajax#4]
it looks like the filter count is not updated any more since v0.7:
it looks good with v0.6:

![Screenshot 2021-03-26 at 10 24 40](https://user-images.githubusercontent.com/16258046/112611263-e3ae9f80-8e1d-11eb-8957-763b44780dfc.png)

**Comment by kpitn** [comment]
Sorry i remove this features in v0.7.
It's now in the last release.

**Comment by Tahuna1** [comment]
looks good now
