### ISSUE TITLE
how to remove underscore and some number in ajax url

### ISSUE THREAD

**Issue by liyakat** [Web200/magento2-elasticsuite-ajax#5]
Hello,

i have some wired issue with extension to use ajax on category pages a url like 

exklusiva-produkter?_=1621684698762&price=69-2105

adding ?_=<some number>  will you please let me know how i can rmeove from url ?

Thank you

**Comment by kpitn** [comment]
Hi,

It comes from cache option in ajax query.
$.ajax({cache: false)

You can test with cache: true, but I had behavioral errors with option set to true.

**Comment by kpitn** [comment]
Fix for caching is in v1.0.0
