### ISSUE TITLE
Missing filter options in IE 11

### ISSUE THREAD

**Issue by dpool** [Web200/magento2-elasticsuite-ajax#6]
Hi, 

we're having some kind of a problem with the display of the filter options in IE 11. Somehow the content inside the ko template is not loaded into the DOM, so the filter options are not being displayed. Please check the screenshots attached. 

Are you providing compatibility for IE 11 or do you have any quick fix idea to get this functionality working again?

Working Screenshots in Chrome:
![image](https://user-images.githubusercontent.com/1866876/123084613-a7410e80-d421-11eb-87e6-113736d5d821.png)
![image](https://user-images.githubusercontent.com/1866876/123084678-b7f18480-d421-11eb-91ba-a1d502a6362d.png)

Missing filters in IE: 
![image](https://user-images.githubusercontent.com/1866876/123084868-eb341380-d421-11eb-8344-78bc0e67861c.png)
![image](https://user-images.githubusercontent.com/1866876/123084943-fe46e380-d421-11eb-9fd2-e3bb95213329.png)

Thanks in advance
Andreas

**Comment by kpitn** [comment]
Sorry I don't try to support ie11
