### ISSUE TITLE
Lazy Load doesn't work after filter

### ISSUE THREAD

**Issue by ely-fornoville** [Web200/magento2-elasticsuite-ajax#7]
After installing the plugin it seems that Lazy Load of our product images on the category pages doesn't work anymore after filtering. Once the AJAX loads new products Lazy Load loading icon keeps loading but no product images are shown.

Is there a fix for this?

Kind regards
Ely

**Comment by ely-fornoville** [comment]
You can test this here: https://acc-ormoda.com/brands/hugo-boss.html
Username: dev 
Password: dev

If you filter images keep loading.
If you filter on only one result images are loading.

**Comment by kpitn** [comment]
Hi,

The module call after loading page : 
`$(document).trigger('contentUpdated');`

So you can call you lazyload like this : 
```
$('body').on('contentUpdated', function() {
    yourLazyloadJs.update();
});
```
